name: Update from Base Template Repository
on:
  # schedule:
  #   - cron: "0 0 * * *" # At 12am everyday
  push:
    branches:
      - "update"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-group

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ github.ref_name }}
    env:
      STAGE_NAME: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Test Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add base https://github.com/Enterprise-CMCS/macpro-base-template.git
          git fetch base
          git branch -D base-update || true
          git checkout -b base-update
          git merge base/production
          git status
